server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:6033/users_sps
    username: root
    password: my_secret_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: pp.comtcoding@gmail.com
    password: balptbfacwfyqojl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true